// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jvvyflqnssqqwjraaisf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp2dnlmbHFuc3NxcXdqcmFhaXNmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwMzk0MjksImV4cCI6MjA2NDYxNTQyOX0.0oneFH_rxMAenQ96USYs1WOloxTwobGIG0KgJu436Io";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);